const REMOVE_REPORT = 'REMOVE_REPORT'
const REMOVE_ALL_REPORTS = 'REMOVE_ALL_REPORTS'
const UPDATE_REPORT = 'UPDATE_REPORT'

module.exports = {
    REMOVE_REPORT,
    REMOVE_ALL_REPORTS,
    UPDATE_REPORT
}
